/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogicgames_libimagequant_LiqHistogram */

#ifndef _Included_com_badlogicgames_libimagequant_LiqHistogram
#define _Included_com_badlogicgames_libimagequant_LiqHistogram
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogicgames_libimagequant_LiqHistogram
 * Method:    _create
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogicgames_libimagequant_LiqHistogram__1create
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogicgames_libimagequant_LiqHistogram
 * Method:    _addImage
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_com_badlogicgames_libimagequant_LiqHistogram__1addImage
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_badlogicgames_libimagequant_LiqHistogram
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogicgames_libimagequant_LiqHistogram__1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
