/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogicgames_libimagequant_LiqResult */

#ifndef _Included_com_badlogicgames_libimagequant_LiqResult
#define _Included_com_badlogicgames_libimagequant_LiqResult
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogicgames_libimagequant_LiqResult
 * Method:    _getRemappingQuality
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogicgames_libimagequant_LiqResult__1getRemappingQuality
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogicgames_libimagequant_LiqResult
 * Method:    _getRemappingError
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_badlogicgames_libimagequant_LiqResult__1getRemappingError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogicgames_libimagequant_LiqResult
 * Method:    _getQuantizationQuality
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogicgames_libimagequant_LiqResult__1getQuantizationQuality
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogicgames_libimagequant_LiqResult
 * Method:    _getQuantizationError
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_badlogicgames_libimagequant_LiqResult__1getQuantizationError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogicgames_libimagequant_LiqResult
 * Method:    _getPalette
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogicgames_libimagequant_LiqResult__1getPalette
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogicgames_libimagequant_LiqResult
 * Method:    _getOutputGamma
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_badlogicgames_libimagequant_LiqResult__1getOutputGamma
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogicgames_libimagequant_LiqResult
 * Method:    _setOutputGamma
 * Signature: (JD)I
 */
JNIEXPORT jint JNICALL Java_com_badlogicgames_libimagequant_LiqResult__1setOutputGamma
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_badlogicgames_libimagequant_LiqResult
 * Method:    _setDitheringLevel
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_com_badlogicgames_libimagequant_LiqResult__1setDitheringLevel
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_badlogicgames_libimagequant_LiqResult
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogicgames_libimagequant_LiqResult__1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
