/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogicgames_libimagequant_LiqPalette */

#ifndef _Included_com_badlogicgames_libimagequant_LiqPalette
#define _Included_com_badlogicgames_libimagequant_LiqPalette
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogicgames_libimagequant_LiqPalette
 * Method:    _getCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_badlogicgames_libimagequant_LiqPalette__1getCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogicgames_libimagequant_LiqPalette
 * Method:    _getColor
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_badlogicgames_libimagequant_LiqPalette__1getColor
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
