/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogicgames_libimagequant_LiqAttribute */

#ifndef _Included_com_badlogicgames_libimagequant_LiqAttribute
#define _Included_com_badlogicgames_libimagequant_LiqAttribute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogicgames_libimagequant_LiqAttribute
 * Method:    _create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_badlogicgames_libimagequant_LiqAttribute__1create
  (JNIEnv *, jclass);

/*
 * Class:     com_badlogicgames_libimagequant_LiqAttribute
 * Method:    _copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogicgames_libimagequant_LiqAttribute__1copy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogicgames_libimagequant_LiqAttribute
 * Method:    _destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_badlogicgames_libimagequant_LiqAttribute__1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
